const TransactionCategoryEnum = Object.freeze({
  HOUSING: "HOUSING",
  TRAVEL: "TRAVEL",
  FOOD: "FOOD",
  UTILITIES: "UTILITIES",
  INSURANCE: "INSURANCE",
  HEALTHCARE: "HEALTHCARE",
  FINANCIAL: "FINANCIAL",
  LIFESTYLE: "LIFESTYLE",
  ENTERTAINMENT: "ENTERTAINMENT",
  MISCELLANEOUS: "MISCELLANEOUS",
});

export default TransactionCategoryEnum;
